### ISSUE TITLE
org.pantsbuild#jmake-1.3.8-7 does not support java 1.6

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/jmake#13]
Errors look like so: https://travis-ci.org/pantsbuild/pants/jobs/47479542
```console
...
03:36:27 00:08         [compile]
03:36:27 00:08           [bootstrap-jmake]DEBUG] Executing: /usr/lib/jvm/java-6-openjdk-amd64/bin/java -Divy.cache.dir=/home/travis/.ivy2/pants -Dsun.io.useCanonCaches=false -cp ../../../.ivy2/pants/org.apache.ivy/ivy/jars/ivy-2.3.0.jar org.apache.ivy.Main -settings /home/travis/build/pantsbuild/pants/build-support/ivy/ivysettings.xml -ivy /home/travis/build/pantsbuild/pants/.pants.d/ivy/b1f0f7d888deba59ac2f77e4f929422e05822284-IvyResolveFingerprintStrategy_53c4bb9c6553/ivy.xml -confs default -cachepath /home/travis/build/pantsbuild/pants/.pants.d/ivy/b1f0f7d888deba59ac2f77e4f929422e05822284-IvyResolveFingerprintStrategy_53c4bb9c6553/classpath.raw.tmp args={'stderr': <pants.rwbuf.read_write_buffer.FileBackedRWBuf object at 0x2deec90>, 'stdout': <pants.rwbuf.read_write_buffer.FileBackedRWBuf object at 0x2dee790>} at cwd=/home/travis/build/pantsbuild/pants
DEBUG] Copied ivy classfile file to /home/travis/build/pantsbuild/pants/.pants.d/ivy/b1f0f7d888deba59ac2f77e4f929422e05822284-IvyResolveFingerprintStrategy_53c4bb9c6553/classpath.raw
03:36:28 00:09           [bootstrap-java-compiler]DEBUG] Executing: /usr/lib/jvm/java-6-openjdk-amd64/bin/java -Divy.cache.dir=/home/travis/.ivy2/pants -Dsun.io.useCanonCaches=false -cp ../../../.ivy2/pants/org.apache.ivy/ivy/jars/ivy-2.3.0.jar org.apache.ivy.Main -settings /home/travis/build/pantsbuild/pants/build-support/ivy/ivysettings.xml -ivy /home/travis/build/pantsbuild/pants/.pants.d/ivy/1589b77554b51ecbd78f75b31c06c723e5bcfea0-IvyResolveFingerprintStrategy_53c4bb9c6553/ivy.xml -confs default -cachepath /home/travis/build/pantsbuild/pants/.pants.d/ivy/1589b77554b51ecbd78f75b31c06c723e5bcfea0-IvyResolveFingerprintStrategy_53c4bb9c6553/classpath.raw.tmp args={'stderr': <pants.rwbuf.read_write_buffer.FileBackedRWBuf object at 0x2ddedd0>, 'stdout': <pants.rwbuf.read_write_buffer.FileBackedRWBuf object at 0x2de4c10>} at cwd=/home/travis/build/pantsbuild/pants
DEBUG] Copied ivy classfile file to /home/travis/build/pantsbuild/pants/.pants.d/ivy/1589b77554b51ecbd78f75b31c06c723e5bcfea0-IvyResolveFingerprintStrategy_53c4bb9c6553/classpath.raw
03:36:31 00:12           [jmake]
                         DEBUG] No ng server found with fingerprint 662b69e083f554fdde9a461b2d98ff967fd8dd92, spawning...
DEBUG] Executing: /usr/lib/jvm/java-6-openjdk-amd64/bin/java -Xmx2G -Dpants.buildroot=/home/travis/build/pantsbuild/pants -Dpants.nailgun.owner=/home/travis/build/pantsbuild/pants/.pants.d/ng/JavaCompile -Dpants.nailgun.fingerprint=662b69e083f554fdde9a461b2d98ff967fd8dd92 -cp .pants.d/ivy/jars/com.martiansoftware/nailgun-server/jars/nailgun-server-0.9.1.jar:.pants.d/ivy/jars/org.pantsbuild/jmake/jars/jmake-1.3.8-7.jar com.martiansoftware.nailgun.NGServer :0 args={'close_fds': True, 'stdin': <open file u'/dev/null', mode 'r' at 0x2d6ef60>, 'stderr': <open file u'/home/travis/build/pantsbuild/pants/.pants.d/ng/JavaCompile/stderr', mode 'w' at 0x2df40c0>, 'stdout': <open file u'/home/travis/build/pantsbuild/pants/.pants.d/ng/JavaCompile/stdout', mode 'w' at 0x2df4030>} at cwd=/home/travis/build/pantsbuild/pants
DEBUG] Spawned ng server with fingerprint 662b69e083f554fdde9a461b2d98ff967fd8dd92 @ 3072
DEBUG] Detected ng server up on port 43417
DEBUG] Found ng server launched with Endpoint(exe='/usr/lib/jvm/java-6-openjdk-amd64/bin/java', fingerprint='662b69e083f554fdde9a461b2d98ff967fd8dd92', pid=3072, port=43417)
DEBUG] Connected to ng server launched with Endpoint(exe='/usr/lib/jvm/java-6-openjdk-amd64/bin/java', fingerprint='662b69e083f554fdde9a461b2d98ff967fd8dd92', pid=3072, port=43417)
DEBUG] Executing via NailgunClient(host=u'localhost', port=43417, workdir='/home/travis/build/pantsbuild/pants'): /usr/lib/jvm/java-6-openjdk-amd64/bin/java -Xmx2G -cp /home/travis/build/pantsbuild/pants/.pants.d/ivy/jars/org.pantsbuild/jmake/jars/jmake-1.3.8-7.jar org.pantsbuild.jmake.Main -classpath .pants.d/ivy/jars/com.google.guava/guava/bundles/guava-16.0.jar:.pants.d/ivy/jars/javax.inject/javax.inject/jars/javax.inject-1.jar:.pants.d/ivy/jars/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar:.pants.d/compile/jvm/apt/classes:.pants.d/compile/jvm/apt/resources:.pants.d/compile/jvm/java/classes:.pants.d/compile/jvm/java/resources:/home/travis/build/pantsbuild/pants/.pants.d/compile/jvm/java/classes -d /home/travis/build/pantsbuild/pants/.pants.d/compile/jvm/java/classes -pdb /home/travis/build/pantsbuild/pants/.pants.d/compile/jvm/java/analysis/artifact_cache_tmpdir/ed843ecb-da04-4b41-a181-6e903b90aae0/examples.src.java.com.pants.examples.annotation.example.example/analysis -pdb-text-format -jcpath /home/travis/build/pantsbuild/pants/.pants.d/ivy/jars/com.twitter.common.tools/java-compiler/jars/java-compiler-0.0.12.jar:/home/travis/build/pantsbuild/pants/.pants.d/ivy/jars/org.fusesource.jansi/jansi/jars/jansi-1.8.jar -jcmainclass com.twitter.common.tools.Compiler -C-source -C6 -C-target -C6 -C-encoding -CUTF-8 -C-g -C-Tcolor -C-Tnowarnprefixes -C/home/travis/build/pantsbuild/pants/.pants.d/gen -C-Tnowarnregex -C^(warning: )?No processor claimed any of these annotations: .* -C-Xlint:all -C-Xlint:-serial -C-Xlint:-path -C-deprecation examples/src/java/com/pants/examples/annotation/example/Example.java
java.lang.UnsupportedClassVersionError: org/pantsbuild/jmake/PublicExceptions$DoubleEntryException : Unsupported major.minor version 51.0
                         	at java.lang.ClassLoader.defineClass1(Native Method)
                         	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
                         	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
                         	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
                         	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
                         	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
                         	at java.security.AccessController.doPrivileged(Native Method)
                         	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
                         	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
                         	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
                         	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
                         	at java.lang.Class.forName0(Native Method)
                         	at java.lang.Class.forName(Class.java:191)
                         	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:242)
                         
FAILURE: Unexpected error - JMake returned 899
...
```

A check of the jar shows all but 3 classes are java 1.7:
```console
jsirois@gill ~/dev-jsirois-pants3 (jsirois/debug/942) $ mkdir /tmp/jmake
jsirois@gill ~/dev-jsirois-pants3 (jsirois/debug/942) $ unzip -qd /tmp/jmake/ ~/.ivy2/pants/org.pantsbuild/jmake/jars/jmake-1.3.8-7.jar 
jsirois@gill ~/dev-jsirois-pants3 (jsirois/debug/942) $ find /tmp/jmake/ -name "*.class" | xargs file
/tmp/jmake/org/pantsbuild/jmake/Base64.class:                                               compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/Base64Test.class:                                           compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/BinaryFileReader.class:                                     compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/BinaryFileWriter.class:                                     compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/BinaryProjectDatabaseReader.class:                          compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/BinaryProjectDatabaseWriter$StringHashTable.class:          compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/BinaryProjectDatabaseWriter.class:                          compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ClassFileReader.class:                                      compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ClassFileReaderTest.class:                                  compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ClassInfo$MethodHandler.class:                              compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ClassInfo.class:                                            compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ClassPath$1.class:                                          compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ClassPath$Dir.class:                                        compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ClassPath$PathEntry.class:                                  compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ClassPath$Zip.class:                                        compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ClassPath.class:                                            compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/CompatibilityChecker$1.class:                               compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/CompatibilityChecker$2.class:                               compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/CompatibilityChecker.class:                                 compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/CompileResult.class:                                        compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/Main.class:                                                 compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/MainTest.class:                                             compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PCDContainer.class:                                         compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PCDEntry.class:                                             compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PCDManager.class:                                           compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PCDManagerTest.class:                                       compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PCDSerializationTest.class:                                 compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PrivateException.class:                                     compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$ClassFileParseException.class:             compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$ClassNameMismatchException.class:          compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$CommandFileReadException.class:            compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$CompilerInteractionException.class:        compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$DoubleEntryException.class:                compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$InternalException.class:                   compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$InvalidCmdOptionException.class:           compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$InvalidSourceFileExtensionException.class: compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$JarDependsOnSourceException.class:         compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$NoActionRequestedException.class:          compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$PDBCorruptedException.class:               compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions.class:                                     compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/RefClassFinder$1.class:                                     compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/RefClassFinder.class:                                       compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/TestCase1.class:                                            compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/TestDepFile.class:                                          compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/TestPCDUtils$1.class:                                       compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/TestPCDUtils.class:                                         compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/TextProjectDatabaseReader.class:                            compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/TextProjectDatabaseWriter.class:                            compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/Utils.class:                                                compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/UtilsTest.class:                                            compiled Java class data, version 51.0
/tmp/jmake/org/pantsbuild/jmake/ant/JavaMake.class:                                         compiled Java class data, version 51.0
```

It seems like the cause is the jarjar post-processing step since the compile step in nbproject/build-impl.xml pins outputs to 1.5 via nbproject/project.properties.  The remedy is either being careful to use an old jdk to publish or else adding a `java -version` parse/check to release.sh.

**Comment by jsirois** [comment]
Version bump: https://github.com/pantsbuild/jmake/commit/fdf335e05e954ae64f329422de8e380eb6df7eb9
Sanity checks for java 1.6 in the release script: https://github.com/pantsbuild/jmake/commit/58635f0ba9167dada14d9fd7997712ca22d65927

**Comment by jsirois** [comment]
I staged a release of 1.3.8-8 like so:
```console
$ JARJAR_JAR=~/downloads/java-libs/jarjar-1.4.jar JAVA=/opt/jdk1.6/bin/java ./release.sh
```

That resulted in:
```console
jsirois@gill ~/dev/3rdparty/jmake (master *) $ mkdir /tmp/jmake
jsirois@gill ~/dev/3rdparty/jmake (master *) $ unzip -qd /tmp/jmake/ dist/release/jmake-renamed.jar 
jsirois@gill ~/dev/3rdparty/jmake (master *) $ find /tmp/jmake -name "*.class" | xargs file
/tmp/jmake/org/pantsbuild/jmake/Base64.class:                                               compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/BinaryFileReader.class:                                     compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/BinaryFileWriter.class:                                     compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/BinaryProjectDatabaseReader.class:                          compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/BinaryProjectDatabaseWriter$StringHashTable.class:          compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/BinaryProjectDatabaseWriter.class:                          compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/ClassFileReader.class:                                      compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/ClassInfo$MethodHandler.class:                              compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/ClassInfo.class:                                            compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/ClassPath$1.class:                                          compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/ClassPath$Dir.class:                                        compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/ClassPath$PathEntry.class:                                  compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/ClassPath$Zip.class:                                        compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/ClassPath.class:                                            compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/CompatibilityChecker$1.class:                               compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/CompatibilityChecker$2.class:                               compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/CompatibilityChecker.class:                                 compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/Main.class:                                                 compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PCDContainer.class:                                         compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PCDEntry.class:                                             compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PCDManager.class:                                           compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PrivateException.class:                                     compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$ClassFileParseException.class:             compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$ClassNameMismatchException.class:          compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$CommandFileReadException.class:            compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$CompilerInteractionException.class:        compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$DoubleEntryException.class:                compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$InternalException.class:                   compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$InvalidCmdOptionException.class:           compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$InvalidSourceFileExtensionException.class: compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$JarDependsOnSourceException.class:         compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$NoActionRequestedException.class:          compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions$PDBCorruptedException.class:               compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/PublicExceptions.class:                                     compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/RefClassFinder$1.class:                                     compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/RefClassFinder.class:                                       compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/TextProjectDatabaseReader.class:                            compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/TextProjectDatabaseWriter.class:                            compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/Utils.class:                                                compiled Java class data, version 49.0 (Java 1.5)
/tmp/jmake/org/pantsbuild/jmake/ant/JavaMake.class:                                         compiled Java class data, version 49.0 (Java 1.5)
```

**Comment by jsirois** [comment]
The release is now live @ https://repo1.maven.org/maven2/org/pantsbuild/jmake/1.3.8-8/
